# Generated by Django 5.2.6 on 2025-09-26 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief description of the incident', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what happened')),
                ('location', models.CharField(help_text='Where did this incident occur?', max_length=200)),
                ('date_occurred', models.DateTimeField(help_text='When did this incident happen?')),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now, help_text='When was this incident reported?')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='How severe was this incident?', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='draft', help_text='Current status of the incident report', max_length=20)),
                ('people_involved', models.TextField(blank=True, help_text='Names of people involved in the incident')),
                ('witnesses', models.TextField(blank=True, help_text='Names of any witnesses')),
                ('injuries_occurred', models.BooleanField(default=False, help_text='Were there any injuries?')),
                ('injury_details', models.TextField(blank=True, help_text='Details of any injuries (if applicable)')),
                ('property_damage', models.BooleanField(default=False, help_text='Was there any property damage?')),
                ('damage_details', models.TextField(blank=True, help_text='Details of property damage (if applicable)')),
                ('immediate_action_taken', models.TextField(blank=True, help_text='What immediate actions were taken?')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the incident was resolved')),
                ('follow_up_required', models.BooleanField(default=False, help_text='Does this incident require follow-up actions?')),
                ('follow_up_details', models.TextField(blank=True, help_text='Details of required follow-up actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(blank=True, help_text='Upload any relevant photos or documents', null=True, upload_to='incident_attachments/')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Manager/supervisor assigned to handle this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(help_text='Staff member who reported this incident', on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('incident_type', models.ForeignKey(help_text='Category of incident', on_delete=django.db.models.deletion.PROTECT, to='incidents.incidenttype')),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-date_occurred', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incidentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='incidents.incidentreport')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
