# Generated by Django 5.2.6 on 2025-09-26 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidenttype',
            options={'ordering': ['name'], 'verbose_name': 'Incident Type', 'verbose_name_plural': 'Incident Types'},
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='date_occurred',
            field=models.DateTimeField(help_text='Exact date and time when the incident occurred'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this report was submitted to the system'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='description',
            field=models.TextField(help_text='Detailed description of what happened, who was involved, and circumstances'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_type',
            field=models.ForeignKey(help_text='Category of incident (Safety, Security, Equipment, etc.)', on_delete=django.db.models.deletion.PROTECT, to='incidents.incidenttype'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(help_text="Specific location (e.g., 'Building A, Floor 2, Conference Room 205')", max_length=200),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='title',
            field=models.CharField(help_text="Brief description of the incident (e.g., 'Slip and fall in cafeteria')", max_length=200),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='color_code',
            field=models.CharField(default='#007bff', help_text='Hex color code for visual representation (e.g., #FF0000)', max_length=7),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this incident type was created'),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of what this incident type covers'),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='name',
            field=models.CharField(help_text='Unique name for this incident type', max_length=100, unique=True),
        ),
    ]
